<?php

/**
 * @file
 * Non-report CiviCRM dashlets 
 * Implements hook_help().
 */
function civicrm_dashlets_help($path = 'admin/help#civicrm_dashlets') {
  switch ($path) {
    case 'admin/help#civicrm_dashlets':
      return t('This module integrates with CiviCRM dashboard to allow custom dashlets.');
  }
}

/**
 * Implements hook_menu().
 */
function civicrm_dashlets_menu() {
  $items = array();
  $items['admin/config/civicrm-dashlets'] = array(
    'title' => 'CiviCRM Dashlets',
    'description' => 'Allows admins to manage CiviCRM Dashlets',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer civicrm_dashlets'),
    'page callback' => 'civicrm_dashlets_settings_form',
  );
  $items['admin/config/civicrm-dashlets/settings'] = array(
    'title' => 'CiviCRM Dashlets Settings',
    'description' => 'Description of your On this date settings page',
    'page arguments' => array('civicrm_dashlets_settings_form'),
    'access arguments' => array('administer civicrm_dashlets'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * User Permissions
 */
function civicrm_dashlets_permission() {
  return array(
    'administer civicrm_dashlets' => array(
      'title' => t('Administer CiviCRM Dashlets'),
      'description' => t('Perform administration tasks for CiviCRM Dashlets.'),
    ),
  );
}

/**
 * @file
 * CiviCRM link in configure your dashboard
 */
function civicrm_dashlets_civicrm_dashboard($contactID, &$contentPlacement)
{
drupal_add_js(drupal_get_path('module', 'civicrm_dashlets') . '/dashlets.js');
}
