<?php

/**
 * @file
 * Add Non-report CiviCRM dashlets 
 * Implements hook_help().
 */
function civicrm_dashlets_help($path = 'admin/help#civicrm_dashlets') {
  switch ($path) {
    case 'admin/help#civicrm_dashlets':
      return t('This module integrates with CiviCRM dashboard to allow custom dashlets.');
  }
}

/**
 * Implements hook_permissions 
 */
function civicrm_dashlets_permission() {
  return array(
    'administer civicrm_dashlets' => array(
      'title' => t('Administer CiviCRM Dashlets'),
      'description' => t('Perform administration tasks for CiviCRM Dashlets.'),
    ),
  );
}

/**
 * Implements hook_civicrm_dashboard 
 * Runs jQuery file to show Add More Dashlets button
 */
function civicrm_dashlets_civicrm_dashboard($contactID, &$contentPlacement) {
  drupal_add_js(drupal_get_path('module', 'civicrm_dashlets') . '/civicrm_dashlets.js');
}

/*
 * Implements hook_civicrm_xmlMenu
 * List's CiviCRM Dashlets Settings Page on Administer CiviCRM page
 */

function civicrm_dashlets_civicrm_xmlMenu(&$files) {
  // Get xml menu file
  $files[] =
      dirname(__FILE__) . DIRECTORY_SEPARATOR .
      'civicrm_dashlets.xml';
}

/*
 * Implements hook_civicrm_config 
 * Sets path for Smarty template and php directories
 */

function civicrm_dashlets_civicrm_config(&$config) {
  $template = & CRM_Core_Smarty::singleton();

  $root = dirname(__FILE__) . DIRECTORY_SEPARATOR;
  $template_dir = $root . 'templates';

  // Add template directory to the Smarty templates path
  if (is_array($template->template_dir)) {
    array_unshift($template->template_dir, $template_dir);
  }
  else {
    $template->template_dir = array($template_dir, $template->template_dir);
  }

  // Add php include path to the Smarty php path
  $include_path = $root . 'php' . DIRECTORY_SEPARATOR . PATH_SEPARATOR . get_include_path();
  set_include_path($include_path);
}