<?php

/**
 * @file
 * Non-report CiviCRM dashlets 
 * Implements hook_help().
 */
function civicrm_dashlets_help($path = 'admin/help#civicrm_dashlets') {
  switch ($path) {
    case 'admin/help#civicrm_dashlets':
      return t('This module integrates with CiviCRM dashboard to allow custom dashlets.');
  }
}

/**
 * Implements hook_menu().
 */
function civicrm_dashlets_menu() {
  $items = array();
  $items['admin/config/civicrm-dashlets'] = array(
    'title' => 'CiviCRM Dashlets',
    'description' => 'Allows admins to manage CiviCRM Dashlets',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer civicrm_dashlets'),
    'page callback' => 'civicrm_dashlets_settings_form',
  );
  $items['admin/config/civicrm-dashlets/settings'] = array(
    'title' => 'CiviCRM Dashlets Settings',
    'description' => 'Description of your On this date settings page',
    'page arguments' => array('civicrm_dashlets_settings_form'),
    'access arguments' => array('administer civicrm_dashlets'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * User Permissions
 */
function civicrm_dashlets_permission() {
  return array(
    'administer civicrm_dashlets' => array(
      'title' => t('Administer CiviCRM Dashlets'),
      'description' => t('Perform administration tasks for CiviCRM Dashlets.'),
    ),
  );
}

/**
 * @file
 * Administration page callbacks for the CiviCRM Dashlets module.
 */
function civicrm_dashlets_civicrm_links( $op, $objectName, $objectId, &$links ) {
  $myLinks = array();
  switch ($objectName) {
    case 'Contact':
      switch ($op) {
        case 'view.contact.activity':
          // Adds a link to the main tab.
          $myLinks[] = array(
            'id' => 'civicrm-dashlets',
            'title' => 'CiviCRM Dashlets',
            'url' => 'civicrm-dashlets/civicrm/actions/'. $objectId,
            'weight' => 10,
            'ref'    => 'civicrm-dashlets' // this is unique identifier for this link
          );
          break;
 
         case 'view.contact.userDashBoard':
           // take the update link and move it to the profile
           $links[CRM_Core_Action::UPDATE]['url'] = 'civicrm/profile/edit';
           $links[CRM_Core_Action::UPDATE]['qs' ] = "reset=1&gid=" . REGSITE_PROFILE_ID . "&id=%%cbid%%";
           break;
 
         case 'create.new.shorcuts':
           // add link to create new profile
           $links[] = array( 'url'   => '/civicrm/admin/uf/group?action=add&reset=1',
                        'title' => ts('CiviCRM Dashlets Shortcuts'),
                        'ref'   => 'civicrm-dashlets');
           break;
      }
  }
  return $myLinks;
}